language: go

script: make build
go:
  - 1.2
  - 1.3
  - tip

install: 
  - export PATH="$HOME/gopath/bin:$PATH"
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GOPATH}/src/github.com/cloudescape/govix
